### PR TITLE
Add AravisGigEController program

### PR DESCRIPTION
**Pull request by David-Estevez**
This PR adds AravisGigEController, a program to control an AravisGigE device with a GUI:

image

This includes:
* Program
* setup.py file to install program integrated in cmake build system
* Installation instructions
* Usage instructions

This fixes:
* https://github.com/roboticslab-uc3m/yarp-devices/issues/145
* https://github.com/roboticslab-uc3m/horus/issues/11
* (probably) https://github.com/roboticslab-uc3m/yarp-devices/issues/125
* (probably) https://github.com/roboticslab-uc3m/yarp-devices/issues/140

### CODE REVIEW

**Comment by David-Estevez** [comment]
Let me rebase this for you to make a nicer merge

**Comment by David-Estevez** [comment]
Rebase done!

**Comment by jgvictores** [comment]
Regarding "branding", is the GUI specific to AravisGigE?

**Comment by jgvictores** [comment]
PS: looks great, can't wait to try!

**Comment by David-Estevez** [comment]
Now that you mention it, I guess you could use it with any device that supports IFrameGrabberControls2... but only if the subset of parameters it controls is present in the device.

**Comment by jgvictores** [comment]
A `cd yarp/src && grep -r IFrameGrabberControls2 *` returns:
```
devices/depthCamera/depthCameraDriver.h: * This device is a YARP plugin for OpenNI2 compatible devices, and exposes the IRGBDSensor and IFrameGrabberControls2
devices/depthCamera/depthCameraDriver.h:                                     public yarp::dev::IFrameGrabberControls2
devices/depthCamera/depthCameraDriver.h:    //IFrameGrabberControls2
libYARP_dev/include/yarp/dev/ServerFrameGrabber.h:    IFrameGrabberControls2 *fgCtrl2;
libYARP_dev/include/yarp/dev/FrameGrabberControl2Impl.h: * This classes implement a sender / parser for IFrameGrabberControls2
libYARP_dev/include/yarp/dev/FrameGrabberControl2Impl.h:class YARP_dev_API yarp::dev::FrameGrabberControls2_Sender: public yarp::dev::IFrameGrabberControls2
libYARP_dev/include/yarp/dev/FrameGrabberControl2Impl.h:    IFrameGrabberControls2 *fgCtrl2;
libYARP_dev/include/yarp/dev/FrameGrabberControl2Impl.h:    bool configure(IFrameGrabberControls2 *interface);
libYARP_dev/include/yarp/dev/FrameGrabberControl2.h:        class IFrameGrabberControls2;
libYARP_dev/include/yarp/dev/FrameGrabberControl2.h: * with former IFrameGrabberControls2 or as standalone.
libYARP_dev/include/yarp/dev/FrameGrabberControl2.h:class YARP_dev_API yarp::dev::IFrameGrabberControls2
libYARP_dev/include/yarp/dev/FrameGrabberControl2.h:    virtual ~IFrameGrabberControls2(){};
libYARP_dev/include/yarp/dev/RemoteFrameGrabber.h:    /* Implementation of IFrameGrabberControls2 interface
libYARP_dev/src/devices/ServerGrabber/ServerGrabber.h:    yarp::dev::IFrameGrabberControls2 *fgCtrl;
libYARP_dev/src/devices/ServerGrabber/ServerGrabber.h:    yarp::dev::IFrameGrabberControls2 *fgCtrl2;
libYARP_dev/src/FrameGrabberControl2Impl.cpp:bool FrameGrabberControls2_Parser::configure(IFrameGrabberControls2* interface)
```

Maybe we could rename this program `grabberControlGUI` or similar?

PS: We have several planned grabbers that may benefit from this GUI.

**Comment by David-Estevez** [comment]
As suggested by @jgvictores I have renamed the program to `grabbercontrols2gui `. 

I've tried to leverage the naming conventions of yarp, Python and PyQt/PySide and some of the resulting names seem a bit weird to me, so if you see something strange please let me know and I'll change it. 

I have also changed the `setup.py` to install everything as a `yarp-devices` package. All the different devices and programs are submodules of this package. This will make things easier when we have more devices / programs.

**Comment by David-Estevez** [comment]
I have also created #149 to make this GUI more generic in the future.

**Pull request merged**
