### PR TITLE
Implement IPositionControl2 on CanBusControlboard (Issue#90)

### PR DESCRIPTION
**Pull request by rsantos88**
* IPositionControlImpl.cpp -> IPositionControl2.cpp 			
* added new IPositionControl2 declarations in CanBusControlboard.hpp 
* added new function declarations in IPositionControl2.cpp

### CODE REVIEW

**Comment by jgvictores** [comment]
Good for starters, but missing implementation!

Most functions should call other functions. In the current state, they're even missing return values. :smile:

**Comment by rsantos88** [comment]
Now, functions are already implemented (3c36a8968fb5699f2a186519abe3cd19162bc546)

**Comment by jgvictores** [comment]
Cool! Now I'd:
1. Work on implementing the `getTarget` functions.
2. Test on the robot. :smile:

**Comment by rsantos88** [comment]
Are the functions well implemented..? (62628c7934602327914d639a776581c0db4d2457)

**Comment by jgvictores** [comment]
Let's make `target` a bit more `target`, e.g. storing position commands in a `std::vector<double>`.

**Comment by rsantos88** [comment]
Executing yarpmotorgui, I've found this error:
```bash
[ERROR]Missing Implementation of getRefVelocity() 
[ERROR]iint->getInteractionlMode failed
```
So, I will proceed to change (IVelocityControlImpl -> IVelocityControl2) and I will implement the new functions.

**Review by jgvictores — APPROVED** [review]
Thank you so much @rsantos88  !!!

**Pull request merged**
