### PR TITLE
Create CanBusPeak device

### PR DESCRIPTION
**Pull request by PeterBowman**
Solves https://github.com/roboticslab-uc3m/yarp-devices/issues/146. This PR has been developed in parallel to https://github.com/roboticslab-uc3m/yarp-devices/pull/158 and integrates all solutions adopted *outside* the CAN device itself (support for message buffers and acceptance filters, new policies, etc.). Its main goal is the creation of another implementation of `yarp::dev::ICanBus` that supports our  new Peak-CAN boards.

Also, basic directory layout is prepared for the upcoming CanBusSocket device.

### CODE REVIEW

**Comment by PeterBowman** [comment]
Tested on TEO and working, please review (:wink: :wink: @jgvictores). Only two issues which I don't consider as blocking for this PR:

* Initialization times have increased. It takes more time to perform all steps in `CanBusControlboard::open()` than before #158.
* If no CAN nodes are present (but configured via .ini), the output is bloated with read errors on close. I need to review the full termination sequence, i.e. whether the CAN device is closed before entering `CanBusControlboard::close()`.

**Review by jgvictores — APPROVED** [review]
LGTM!

Ok to merge?

**Comment by PeterBowman** [comment]
> Ok to merge?

Yeah. I'll be working on the increased init times with the current HiCO.CAN setup in the next days. Termination issues shouldn't require real hardware for being debugged (CanBusFake + FakeJoint).

**Comment by PeterBowman** [comment]
Follow-ups:
* https://github.com/roboticslab-uc3m/yarp-devices/issues/191 (transmit delays)
* https://github.com/roboticslab-uc3m/yarp-devices/commit/9e7c30923bc399dcf282aa1501ef3aaf6f9cd8df (forgot to properly initialize a C structure)

**Pull request merged**
