### PR TITLE
Applied absolute value for tr in setMinLimitRaw and setMaxLimitRaw

### PR DESCRIPTION
**Pull request by rsantos88**
Applied absolute value for tr in `setMinLimitRaw` and `setMaxLimitRaw` to configure the driver correctly with the new direction of rotations.

### CODE REVIEW

**Comment by PeterBowman** [comment]
Requires testing. BTW this could have been opened as a draft PR!

**Review by PeterBowman — CHANGES_REQUESTED** [review]
* Please `#include <cmath>` and use `std::abs()` instead of `abs()`.
* I think that min-max values should be reversed when working with negative tr's. Am I right?
* Can we broaden the scope of this PR to cover the review of velocity/acceleration reference values, too? Perhaps the same `abs` treatment should be applied in `setRefSpeedRaw` and `setRefAccelerationRaw`.
* Similarly in *ICanBusSharerImpl.cpp*, look for the `refSpeed` and `refAcceleration` class members.

**Comment by rsantos88** [comment]
> * I think that min-max values should be reversed when working with negative tr's. Am I right?

These changes have already been made in the .ini files. See: https://github.com/roboticslab-uc3m/teo-main/issues/39#issuecomment-466986628 example of the right elbow by @jgvictores.

> * Please `#include <cmath>` and use `std::abs()` instead of `abs()`.
> * Can we broaden the scope of this PR to cover the review of velocity/acceleration reference values, too? Perhaps the same `abs` treatment should be applied in `setRefSpeedRaw` and `setRefAccelerationRaw`.
> * Similarly in *ICanBusSharerImpl.cpp*, look for the `refSpeed` and `refAcceleration` class members.

Changes applied in the last 2 commits

**Review by PeterBowman — APPROVED** [review]

**Comment by PeterBowman** [comment]
Follow-up: https://github.com/roboticslab-uc3m/yarp-devices/issues/213.

**Pull request merged**
