### PR TITLE
Remove duplicate install clauses

### LINKED ISSUE #112: Redundant install clause in CMake files
It seems that we have redundant install clauses in CMake files that may cause `yarpdev` to crash.

For instance, in `libraries/BodyYarp/Jre/CMakeListst.txt`, [line 19](https://github.com/roboticslab-uc3m/yarp-devices/blob/0967a88a7e00a6f995118f7db57eb4609cc7660a/libraries/BodyYarp/Jr3/CMakeLists.txt#L19): 
```
  install(TARGETS Jr3 DESTINATION lib)
```
Is no longer required due to `yarp_add_plugin`

### PR DESCRIPTION
**Pull request by David-Estevez**
Fixes #112 

I've removed all entries I found, but I've not checked the code since I don't have currently access to the robot's hardware.

### CODE REVIEW

**Comment by jgvictores** [comment]
Looks great, I'm just a bit afraid of conflict with an incoming PR from:
https://github.com/roboticslab-uc3m/yarp-devices/issues/106#issuecomment-290716819

Let's wait to merge that bigger one before this one. Thanks!!!

**Comment by jgvictores** [comment]
...https://github.com/roboticslab-uc3m/yarp-devices/issues/106#issuecomment-290716819 has materialized in #114

**Comment by David-Estevez** [comment]
I'll wait and update when #114  is merged

**Comment by jgvictores** [comment]
Thanks!!!

**Pull request merged**
