### PR TITLE
New more simple code for lacquey-fetch adapted to the new firmware

### PR DESCRIPTION
**Pull request by rsantos88**
Only one byte to send the order of the hand movement.
Hand values sended to mbed:
*  0  loose hand
*  1  open hand
* -1  close hand

### CODE REVIEW

**Comment by jgvictores** [comment]
There was a reason for sending more than 3 different values: being able to control the grip torque.

Obviating that fact (it has passive compliance anyway), some of the minimum requirements would be the following:
- [ ] It seems the following line could be reduced to `uint8_t msg_position_target[]= {0x00}` (remove comment on 8 bytes): https://github.com/roboticslab-uc3m/yarp-devices/blob/a101bc52e883dd4f84788212b6104dc28b0e6d4e/libraries/YarpPlugins/LacqueyFetch/IPositionControl2RawImpl.cpp#L36
- [ ] Move https://os.mbed.com/users/raulsr988/code/LacqueyFetch/file/3b3e8f8352a8/main.cpp to https://github.com/roboticslab-uc3m/yarp-devices/tree/develop/firmware/LacqueyFetch
- [ ] Are the other two files in https://os.mbed.com/users/raulsr988/code/LacqueyFetch required?
- [ ] Document the mbed firmware registering/compiling/downloading/uploading process in https://github.com/roboticslab-uc3m/yarp-devices/blob/develop/firmware/LacqueyFetch/README.md
- [x] ~~Change `-1` to `2` and use unsigned chars (only 8-bit assured by C) on both ends.~~ ((see comment on legacy protocol, below))

**Comment by rsantos88** [comment]
In views of the [legacy-PIC code](https://github.com/roboticslab-uc3m/yarp-devices/blob/cccde54d43bc3c0d9bd2acdc25b5977ca69aae88/firmware/LacqueyFetch/legacy-PIC.tar.gz), protocol will be:
```
0xA0 -> Mantener abriendo
0xC0 -> Mantener cerrando
0xF0 -> Parar (dejar de actuar, enable a 0)
```

**Comment by rsantos88** [comment]
Now, the mbed firmware of `lacqueyFetch` is compatible with the code of the old hand PIC. Therefore, tt's not necessary to do this PR.
See the changes here: https://os.mbed.com/users/raulsr988/code/LacqueyFetch/rev/8ebb11ba21be/
It works fine.

**Comment by jgvictores** [comment]
Okay, perfect! Thanks, closing!!

**Pull request closed without merging**
